import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { faMugHot } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mb-16">
          <div className="max-w-2xl mx-auto px-4 py-4 flex justify-between items-center">
            {/* Logo Section */}
            <div>
              <Link href={"/"} className="inline-flex gap-1 items-center">
                <FontAwesomeIcon className="h-8" icon={faMugHot} />
                <span className="mt-2">Buy me a coffee</span>
              </Link>
            </div>

            {/* Navigation Section */}
            <nav className="flex gap-4 mt-0.5">
              <Link href="/about">About</Link>
              <Link href="/faq">FAQ</Link>
              <Link href="/contact">Contact</Link>
            </nav>

            {/* Login/Signup Section */}
            <div className="flex gap-4">
              <button className="border-2 px-4 py-2 rounded-full">Login</button>
              <button className="bg-yellow-300 rounded-full px-4 py-2">Sign up</button>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
